# Generated by Django 4.2.13 on 2026-06-02 18:07

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Department = apps.get_model('accounts', 'Department')

    department_map = {}
    for profile in Profile.objects.exclude(department_text__isnull=True).exclude(department_text=''):
        department_name = profile.department_text.strip()
        if not department_name:
            continue
        department = department_map.get(department_name)
        if department is None:
            department, _ = Department.objects.get_or_create(name=department_name)
            department_map[department_name] = department
        profile.department = department
        if profile.role == 'instructor':
            profile.role = 'security_officer'
        profile.save(update_fields=['department', 'role'])

    Profile.objects.filter(role='instructor').update(role='security_officer')


def backwards(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')

    for profile in Profile.objects.select_related('department'):
        profile.department_text = profile.department.name if profile.department_id else ''
        if profile.role == 'security_officer':
            profile.role = 'instructor'
        profile.save(update_fields=['department_text', 'role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='department_text',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('security_officer', 'Ответственный за ИБ'), ('admin', 'Администратор')], default='employee', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='profile',
            name='department_text',
        ),
    ]
