# Generated by Django 4.2.13 on 2026-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('ldap', 'LDAP'), ('active_directory', 'Active Directory')], max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('imported_departments', models.PositiveIntegerField(default=0)),
                ('imported_positions', models.PositiveIntegerField(default=0)),
                ('imported_users', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
