# Generated by Django 4.2.13 on 2026-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
